name: Build
on: [workflow_dispatch]
jobs:
  job0:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "你好！👋"
      - run: uname -a
      - run: lsb_release -a
      - name: Checking out repo
        uses: actions/checkout@v4
      - name: Listing files
        run: ls -R .
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: web
          target: next
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
